### ISSUE TITLE
Sales Rep - RMA Inquiry - Revisions Requested

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#86]
On RMA inquiry, we want it to work like the other inquiry screens, so make the following changes:

- It should automatically filter by the selected account.
- Due to the above, we can hide the customer name column.
- The filter box didn't seem to do anything for me.  For consistency, remove it or add a similar functioning filter to all of the other inquiry screens.
- The column alignment in the drill-downs is off.
- On quantity columns, do a right-align.
- On the drill-down view the column headers click as if they would be sortable but are not sorting. Either disable the clicking to make them not appear sortable or fix the sorting.
- See if you can get the height of the date fields to match that of the search button.

**Comment by aellis** [comment]
In relation to the filter not working - there was actually an error thrown out to the console:

Cannot read property 'getElementsByTagName' of null
    at Object.Filter [as filter] (https://cdn.rawgit.com/bezlio/bezlio-apps/development/roles/sales-rep/rma-inquiry/js/rma.js:46:50)
    at eval (eval at onDataChange.f.method.component.bezl.functions.(anonymous function) (https://portal-staging.bezl.io/bundles/app.bundle.min.js:9:5142), <anonymous>:2:15)
    at Object.execCb (https://portal-staging.bezl.io/node_modules/requirejs/require.js:1693:33)
    at Module.check (https://portal-staging.bezl.io/node_modules/requirejs/require.js:881:51)
    at Module.enable (https://portal-staging.bezl.io/node_modules/requirejs/require.js:1173:22)
    at Module.init (https://portal-staging.bezl.io/node_modules/requirejs/require.js:786:26)
    at https://portal-staging.bezl.io/node_modules/requirejs/require.js:1457:36
    at e.invokeTask (https://portal-staging.bezl.io/node_modules/zone.js/dist/zone.min.js:1:15126)
    at Object.onInvokeTask (https://portal-staging.bezl.io/bundles/dependencies.bundle.min.js:54:30236)
    at e.invokeTask (https://portal-staging.bezl.io/node_modules/zone.js/dist/zone.min.js:1:15062)
    at n.runTask (https://portal-staging.bezl.io/node_modules/zone.js/dist/zone.min.js:1:12486)
    at invoke (https://portal-staging.bezl.io/node_modules/zone.js/dist/zone.min.js:1:16239)
